name: firebase_database_web
description: The web implementation of firebase_database
version: 0.2.5+11
homepage: https://github.com/firebase/flutterfire/tree/master/packages/firebase_database/firebase_database_web

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  collection: ^1.18.0
  firebase_core:
    git:
      url: https://github.com/Jparrgam/flutterfire.git
      ref: master
      path: packages/firebase_core/firebase_core
  firebase_core_web:
    git:
      url: https://github.com/Jparrgam/flutterfire.git
      ref: master
      path: packages/firebase_core/firebase_core_web
  firebase_database_platform_interface:
    git:
      url: https://github.com/Jparrgam/flutterfire.git
      ref: master
      path: packages/firebase_core/firebase_core_platform_interface
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

dev_dependencies:
  firebase_core_platform_interface:
    git:
      url: https://github.com/Jparrgam/flutterfire.git
      ref: master
      path: packages/firebase_core/firebase_core_platform_interface
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0


flutter:
  plugin:
    platforms:
      web:
        pluginClass: FirebaseDatabaseWeb
        fileName: firebase_database_web.dart
